import type {
  LibraryDetail,
  LibrarySummary,
  TargetView,
  AdapterInfo,
  SyncPlanView,
  TaskSnapshot,
  HistoryPage,
  BackupStats,
  SnapshotView,
} from '../lib/backend-contract';

export const MOCK_LIBRARIES: LibrarySummary[] = [
  {
    libraryId: 'lib-001',
    displayName: '我的个人 Skills 库',
    canonicalPath: 'D:\\Work\\my-skills',
    sourceRoot: 'D:\\Work\\my-skills',
    pinned: true,
    lastOpenedAt: '2026-09-08T04:30:00Z',
    pathValid: true,
    skillCount: 4,
    invalidCount: 1,
  },
  {
    libraryId: 'lib-002',
    displayName: '团队共享 Skills 集合',
    canonicalPath: 'D:\\Projects\\team-repo\\skills',
    sourceRoot: 'D:\\Projects\\team-repo\\skills',
    pinned: false,
    lastOpenedAt: '2026-09-07T11:20:00Z',
    pathValid: true,
    skillCount: 12,
    invalidCount: 0,
  },
];

export const MOCK_TARGETS: TargetView[] = [
  {
    targetId: 'tgt-codex',
    physicalTargetId: 'ptgt-codex',
    adapterId: 'codex',
    displayName: 'Codex (用户级)',
    scope: 'user',
    resolvedPath: 'C:\\Users\\23167\\.agents\\skills',
    resolutionSource: '用户目录预设 (USERPROFILE)',
    availability: 'exists',
    sharedWithTools: ['Codex', 'Cursor'],
    mappedSkillCount: 3,
    enabled: true,
  },
  {
    targetId: 'tgt-claude',
    physicalTargetId: 'ptgt-claude',
    adapterId: 'claude_code',
    displayName: 'Claude Code (用户级)',
    scope: 'user',
    resolvedPath: 'C:\\Users\\23167\\.claude\\skills',
    resolutionSource: '用户目录预设 (USERPROFILE)',
    availability: 'exists',
    sharedWithTools: ['Claude Code'],
    mappedSkillCount: 3,
    enabled: true,
  },
  {
    targetId: 'tgt-cursor',
    physicalTargetId: 'ptgt-cursor',
    adapterId: 'cursor',
    displayName: 'Cursor (用户级)',
    scope: 'user',
    resolvedPath: 'C:\\Users\\23167\\.cursor\\skills',
    resolutionSource: '用户目录预设 (USERPROFILE)',
    availability: 'will_create',
    sharedWithTools: ['Cursor'],
    mappedSkillCount: 2,
    enabled: true,
  },
  {
    targetId: 'tgt-copilot',
    physicalTargetId: 'ptgt-copilot',
    adapterId: 'copilot_vscode',
    displayName: 'GitHub Copilot (用户级)',
    scope: 'user',
    resolvedPath: 'C:\\Users\\23167\\.copilot\\skills',
    resolutionSource: '用户目录预设 (USERPROFILE)',
    availability: 'exists',
    sharedWithTools: ['GitHub Copilot'],
    mappedSkillCount: 1,
    enabled: true,
  },
];

export const MOCK_ADAPTERS: AdapterInfo[] = [
  {
    adapterId: 'codex',
    displayName: 'Codex',
    adapterVersion: '1.2.0',
    verifiedAt: '2026-09-08',
    docsUrl: 'https://learn.chatgpt.com/docs/build-skills',
    scopes: ['user', 'project'],
    userTemplate: '%USERPROFILE%/.agents/skills',
    projectTemplate: '<projectRoot>/.agents/skills',
    resolved: {
      user: {
        path: 'C:\\Users\\23167\\.agents\\skills',
        source: '系统环境变量',
        availability: 'exists',
        detail: '目录已就绪且可写',
      },
      project: null,
    },
    detectedHints: ['检测到本地已存在 .agents 目录'],
    alsoReadBy: ['Cursor', 'GitHub Copilot'],
    notes: ['优先推荐放置于用户目录'],
  },
  {
    adapterId: 'claude_code',
    displayName: 'Claude Code',
    adapterVersion: '1.0.0',
    verifiedAt: '2026-09-08',
    docsUrl: 'https://code.claude.com/docs/en/skills',
    scopes: ['user', 'project'],
    userTemplate: '%USERPROFILE%/.claude/skills',
    projectTemplate: '<projectRoot>/.claude/skills',
    resolved: {
      user: {
        path: 'C:\\Users\\23167\\.claude\\skills',
        source: '系统环境变量',
        availability: 'exists',
        detail: '目录已就绪且可写',
      },
      project: null,
    },
    detectedHints: ['检测到配置文件 CLAUDE.md'],
    alsoReadBy: [],
    notes: ['支持通过 CLAUDE_CONFIG_DIR 自定义'],
  },
  {
    adapterId: 'cursor',
    displayName: 'Cursor',
    adapterVersion: '0.42.0',
    verifiedAt: '2026-09-08',
    docsUrl: 'https://prod.cursor.com/docs/skills',
    scopes: ['user', 'project'],
    userTemplate: '%USERPROFILE%/.cursor/skills',
    projectTemplate: '<projectRoot>/.cursor/skills',
    resolved: {
      user: {
        path: 'C:\\Users\\23167\\.cursor\\skills',
        source: '系统环境变量',
        availability: 'will_create',
        detail: '目标文件夹尚不存在，将在同步时自动创建',
      },
      project: null,
    },
    detectedHints: [],
    alsoReadBy: [],
    notes: ['Cursor 亦兼容读取 .agents 及 .claude 目录'],
  },
  {
    adapterId: 'copilot_vscode',
    displayName: 'GitHub Copilot (VS Code)',
    adapterVersion: '1.93.0',
    verifiedAt: '2026-09-08',
    docsUrl: 'https://code.visualstudio.com/docs/agent-customization/agent-skills',
    scopes: ['user', 'project'],
    userTemplate: '%USERPROFILE%/.copilot/skills',
    projectTemplate: '<projectRoot>/.github/skills',
    resolved: {
      user: {
        path: 'C:\\Users\\23167\\.copilot\\skills',
        source: '系统环境变量',
        availability: 'exists',
        detail: '目录已就绪且可写',
      },
      project: null,
    },
    detectedHints: ['已检测到 VS Code 安装环境'],
    alsoReadBy: [],
    notes: ['项目级通常建议放置在 .github/skills'],
  },
];

export const MOCK_LIBRARY_DETAIL: LibraryDetail = {
  summary: MOCK_LIBRARIES[0],
  ignorePatterns: ['**/.git/**', '**/node_modules/**', '**/__pycache__/**', '**/*.tmp'],
  configVersion: 3,
  skills: [
    {
      skillId: 'sk-001',
      relPath: 'code-review',
      name: 'code-review',
      description: '对 Git 提交或变更代码进行自动化审查，识别潜在缺陷与性能漏洞',
      fileCount: 5,
      totalBytes: 24800,
      lastContentChangedAt: '2026-09-08T03:15:00Z',
      digest: 'sha256:4a8b79f8c61e2f3d',
      validation: {
        status: 'valid',
        issues: [],
      },
      targets: {
        'ptgt-codex': {
          state: 'synced',
          mappingId: 'map-01',
          targetDirName: 'code-review',
          detail: '目标与源版本一致 (S=T=B)',
        },
        'ptgt-claude': {
          state: 'source_updated',
          mappingId: 'map-02',
          targetDirName: 'code-review',
          detail: '源文件有改动，目标为旧基线版本 (S≠B, T=B)',
        },
        'ptgt-cursor': {
          state: 'source_updated',
          mappingId: 'map-03',
          targetDirName: 'code-review',
          detail: '源端有 2 处更新待同步',
        },
        'ptgt-copilot': {
          state: 'no_mapping',
          mappingId: null,
          targetDirName: null,
          detail: '未分配到此工具',
        },
      },
    },
    {
      skillId: 'sk-002',
      relPath: 'meeting-notes',
      name: 'meeting-notes',
      description: '结构化会议记录提取与待办行动项分配提示词',
      fileCount: 3,
      totalBytes: 12400,
      lastContentChangedAt: '2026-09-07T18:00:00Z',
      digest: 'sha256:9f8e7d6c5b4a3120',
      validation: {
        status: 'valid',
        issues: [],
      },
      targets: {
        'ptgt-codex': {
          state: 'to_add',
          mappingId: 'map-04',
          targetDirName: 'meeting-notes',
          detail: '目标目录尚不存在，准备创建',
        },
        'ptgt-claude': {
          state: 'to_add',
          mappingId: 'map-05',
          targetDirName: 'meeting-notes',
          detail: '目标目录尚不存在，准备创建',
        },
        'ptgt-cursor': {
          state: 'no_mapping',
          mappingId: null,
          targetDirName: null,
          detail: '未配置映射',
        },
        'ptgt-copilot': {
          state: 'synced',
          mappingId: 'map-06',
          targetDirName: 'meeting-notes',
          detail: '内容一致已对齐',
        },
      },
    },
    {
      skillId: 'sk-003',
      relPath: 'release-helper',
      name: 'release-helper',
      description: '生成语义化版本发布 Changelog 与 GitHub Release 草稿',
      fileCount: 6,
      totalBytes: 38200,
      lastContentChangedAt: '2026-09-08T01:30:00Z',
      digest: 'sha256:1a2b3c4d5e6f7a8b',
      validation: {
        status: 'valid',
        issues: [],
      },
      targets: {
        'ptgt-codex': {
          state: 'synced',
          mappingId: 'map-07',
          targetDirName: 'release-helper',
          detail: '已与目标保持同步',
        },
        'ptgt-claude': {
          state: 'target_modified',
          mappingId: 'map-08',
          targetDirName: 'release-helper',
          detail: '目标端检测到本地文件修改 (S=B, T≠B)，存在冲突',
        },
        'ptgt-cursor': {
          state: 'unmanaged_conflict',
          mappingId: 'map-09',
          targetDirName: 'release-helper',
          detail: '目标存在同名非托管目录，且内容不同',
        },
        'ptgt-copilot': {
          state: 'no_mapping',
          mappingId: null,
          targetDirName: null,
          detail: null,
        },
      },
    },
    {
      skillId: 'sk-004',
      relPath: 'data-pipeline',
      name: 'data-pipeline',
      description: '数据清洗与 ETL 脚本辅助提示词',
      fileCount: 2,
      totalBytes: 8900,
      lastContentChangedAt: '2026-09-06T12:00:00Z',
      digest: 'sha256:3344556677889900',
      validation: {
        status: 'invalid',
        issues: [
          {
            code: 'yaml_syntax_error',
            message: 'SKILL.md 第 4 行 YAML 键值解析错误，缺少冒号后的空格',
            line: 4,
            column: 12,
          },
        ],
      },
      targets: {
        'ptgt-codex': {
          state: 'invalid',
          mappingId: null,
          targetDirName: 'data-pipeline',
          detail: '元数据校验失败，禁止同步',
        },
        'ptgt-claude': {
          state: 'invalid',
          mappingId: null,
          targetDirName: 'data-pipeline',
          detail: '元数据校验失败，禁止同步',
        },
        'ptgt-cursor': {
          state: 'no_mapping',
          mappingId: null,
          targetDirName: null,
          detail: null,
        },
        'ptgt-copilot': {
          state: 'no_mapping',
          mappingId: null,
          targetDirName: null,
          detail: null,
        },
      },
    },
  ],
};

export const MOCK_SYNC_PLAN: SyncPlanView = {
  planId: 'plan-101',
  planVersion: 1,
  libraryId: 'lib-001',
  operation: 'sync',
  status: 'active',
  createdAt: '2026-09-08T05:00:00Z',
  configVersion: 3,
  groups: [
    {
      physicalTargetId: 'ptgt-claude',
      targetPath: 'C:\\Users\\23167\\.claude\\skills',
      sharedWithTools: ['Claude Code'],
      items: [
        {
          itemId: 'item-01',
          mappingId: 'map-02',
          skillId: 'sk-001',
          skillName: 'code-review',
          relPath: 'code-review',
          action: 'update',
          fileChanges: [
            {
              kind: 'update',
              relPath: 'SKILL.md',
              bytes: 3420,
              sourceDigest: 'sha256:aaa111',
              targetDigest: 'sha256:bbb222',
              diffPreviewable: true,
            },
            {
              kind: 'add',
              relPath: 'references/best-practices.md',
              bytes: 8120,
              sourceDigest: 'sha256:ccc333',
              targetDigest: null,
              diffPreviewable: true,
            },
          ],
          excludedByIgnore: [],
          needsBackup: true,
          targetPath: 'C:\\Users\\23167\\.claude\\skills\\code-review',
          stateBefore: 'source_updated',
          conflict: null,
          blockedReason: null,
          selected: true,
          decision: null,
        },
        {
          itemId: 'item-02',
          mappingId: 'map-08',
          skillId: 'sk-003',
          skillName: 'release-helper',
          relPath: 'release-helper',
          action: 'skip',
          fileChanges: [
            {
              kind: 'update',
              relPath: 'SKILL.md',
              bytes: 2500,
              sourceDigest: 'sha256:ddd444',
              targetDigest: 'sha256:eee555',
              diffPreviewable: true,
            },
          ],
          excludedByIgnore: [],
          needsBackup: true,
          targetPath: 'C:\\Users\\23167\\.claude\\skills\\release-helper',
          stateBefore: 'target_modified',
          conflict: {
            kind: 'target_modified',
            message: '目标端检测到文件改动。为了防止数据覆盖丢失，请确认处理方案。',
            availableChoices: ['keep_target', 'overwrite_with_source', 'pause_mapping'],
          },
          blockedReason: null,
          selected: false,
          decision: null,
        },
      ],
    },
    {
      physicalTargetId: 'ptgt-cursor',
      targetPath: 'C:\\Users\\23167\\.cursor\\skills',
      sharedWithTools: ['Cursor'],
      items: [
        {
          itemId: 'item-03',
          mappingId: 'map-03',
          skillId: 'sk-001',
          skillName: 'code-review',
          relPath: 'code-review',
          action: 'update',
          fileChanges: [
            {
              kind: 'update',
              relPath: 'SKILL.md',
              bytes: 3420,
              sourceDigest: 'sha256:aaa111',
              targetDigest: 'sha256:bbb222',
              diffPreviewable: true,
            },
          ],
          excludedByIgnore: [],
          needsBackup: true,
          targetPath: 'C:\\Users\\23167\\.cursor\\skills\\code-review',
          stateBefore: 'source_updated',
          conflict: null,
          blockedReason: null,
          selected: true,
          decision: null,
        },
      ],
    },
  ],
  summary: {
    createCount: 0,
    updateCount: 2,
    removeCount: 0,
    restoreCount: 0,
    skipCount: 1,
    conflictCount: 1,
    blockedCount: 0,
    executableCount: 2,
    totalBytes: 14960,
  },
};

export const MOCK_TASK_SNAPSHOT: TaskSnapshot = {
  taskId: 'task-sync-999',
  kind: 'sync',
  trigger: 'manual',
  status: 'running',
  createdAt: '2026-09-08T05:10:00Z',
  startedAt: '2026-09-08T05:10:01Z',
  finishedAt: null,
  counts: {
    success: 1,
    failed: 0,
    skipped: 1,
    conflictPending: 0,
    cancelled: 0,
    total: 2,
  },
  items: [
    {
      itemId: 'titem-1',
      mappingId: 'map-03',
      skillName: 'code-review (Cursor)',
      targetPath: 'C:\\Users\\23167\\.cursor\\skills\\code-review',
      action: 'update',
      status: 'success',
      error: null,
      bytesProcessed: 3420,
      bytesTotal: 3420,
      snapshotId: 'snap-001',
    },
    {
      itemId: 'titem-2',
      mappingId: 'map-02',
      skillName: 'code-review (Claude Code)',
      targetPath: 'C:\\Users\\23167\\.claude\\skills\\code-review',
      action: 'update',
      status: 'running',
      error: null,
      bytesProcessed: 4096,
      bytesTotal: 11540,
      snapshotId: null,
    },
  ],
  error: null,
};

export const MOCK_HISTORY: HistoryPage = {
  items: [
    {
      taskId: 'task-hist-001',
      kind: 'sync',
      trigger: 'manual',
      startedAt: '2026-09-08T03:00:00Z',
      durationMs: 840,
      status: 'completed',
      counts: {
        success: 3,
        failed: 0,
        skipped: 0,
        conflictPending: 0,
        cancelled: 0,
        total: 3,
      },
      libraryName: '我的个人 Skills 库',
      targetPaths: ['C:\\Users\\23167\\.agents\\skills', 'C:\\Users\\23167\\.claude\\skills'],
    },
    {
      taskId: 'task-hist-002',
      kind: 'sync',
      trigger: 'retry',
      startedAt: '2026-09-07T16:20:00Z',
      durationMs: 1250,
      status: 'partial',
      counts: {
        success: 2,
        failed: 1,
        skipped: 0,
        conflictPending: 0,
        cancelled: 0,
        total: 3,
      },
      libraryName: '我的个人 Skills 库',
      targetPaths: ['C:\\Users\\23167\\.cursor\\skills'],
    },
  ],
  nextCursor: null,
};

export const MOCK_BACKUP_STATS: BackupStats = {
  totalBytes: 485000000, // 约 462 MB
  reclaimableBytes: 152000000, // 约 145 MB
  protectedBytes: 333000000, // 约 317 MB
  retentionDays: 30,
  softCapBytes: 2147483648, // 2 GiB
};

export const MOCK_SNAPSHOTS: SnapshotView[] = [
  {
    snapshotId: 'snap-20260908-01',
    taskItemId: 'item-hist-1',
    mappingId: 'map-02',
    targetPath: 'C:\\Users\\23167\\.claude\\skills\\code-review',
    existedBefore: true,
    digest: 'sha256:fe8910a9b8',
    bytes: 23100,
    pinned: true,
    available: true,
    createdAt: '2026-09-08T03:00:00Z',
  },
  {
    snapshotId: 'snap-20260907-02',
    taskItemId: 'item-hist-2',
    mappingId: 'map-02',
    targetPath: 'C:\\Users\\23167\\.claude\\skills\\code-review',
    existedBefore: true,
    digest: 'sha256:7766554433',
    bytes: 21800,
    pinned: false,
    available: true,
    createdAt: '2026-09-07T16:20:00Z',
  },
];
