#!/usr/bin/env python3
"""Initialize or sync a pytest-playwright multi-agent Web test harness."""

from __future__ import annotations

import argparse
import os
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SKILL_DIR = Path(__file__).resolve().parents[1]
TEMPLATES_DIR = SKILL_DIR / "assets" / "templates"
PROFILE_NAME = "harness.project.yaml"
MANAGED_FILE_MARKER = "MANAGED-BY: init-harness"


@dataclass
class Operation:
    action: str
    path: Path
    detail: str
    destructive: bool = False


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "":
        return ""
    if value.lower() in {"true", "false"}:
        return value.lower() == "true"
    if value in {"null", "None", "~"}:
        return None
    if (value.startswith('"') and value.endswith('"')) or (
        value.startswith("'") and value.endswith("'")
    ):
        return value[1:-1]
    return value


def parse_minimal_yaml(text: str) -> dict[str, Any]:
    """Parse the small harness.project.yaml subset without PyYAML."""

    root: dict[str, Any] = {}
    section: str | None = None
    list_key: str | None = None

    for raw_line in text.splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#"):
            continue
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        line = raw_line.strip()

        if indent == 0:
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            key = key.strip()
            value = value.strip()
            if value == "":
                root[key] = {}
                section = key
                list_key = None
            else:
                root[key] = parse_scalar(value)
                section = None
                list_key = None
            continue

        if indent == 2 and section:
            if ":" not in line:
                continue
            key, value = line.split(":", 1)
            key = key.strip()
            value = value.strip()
            if value == "":
                root.setdefault(section, {})[key] = []
                list_key = key
            else:
                root.setdefault(section, {})[key] = parse_scalar(value)
                list_key = None
            continue

        if indent == 4 and section and list_key and line.startswith("- "):
            root.setdefault(section, {}).setdefault(list_key, []).append(
                parse_scalar(line[2:])
            )

    return root


def load_profile(path: Path) -> dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    try:
        import yaml  # type: ignore

        data = yaml.safe_load(text) or {}
        if not isinstance(data, dict):
            raise ValueError("profile root must be a mapping")
        return data
    except ModuleNotFoundError:
        return parse_minimal_yaml(text)


def profile_draft(project_root: Path) -> str:
    project_name = project_root.name
    return f"""# Generated by init-harness. Fill this file, then rerun the skill.
project_name: {project_name}
base_url: https://example.com

paths:
  tests_dir: tests
  data_dir: data
  page_map_dir: page_map
  artifacts_dir: artifacts

runner:
  test_command: python -m pytest tests/ -v

auth:
  needs_auth: true
  auth_mode: basic
  login_url: /login
  username_env: E2E_USERNAME
  password_env: E2E_PASSWORD
  username_selector: 'input[name="email"]'
  password_selector: 'input[name="password"]'
  submit_selector: 'button[type="submit"]'
  post_login_url_pattern: /dashboard

project_contract:
  primary_flows:
    - Replace with the first small business flow to test
  notes:
    - Replace with important project constraints
"""


def norm_section(profile: dict[str, Any], key: str) -> dict[str, Any]:
    value = profile.get(key) or {}
    if not isinstance(value, dict):
        return {}
    return value


def path_value(profile: dict[str, Any], section: str, key: str, default: str) -> str:
    return str(norm_section(profile, section).get(key) or default)


def scalar(profile: dict[str, Any], section: str, key: str, default: str = "") -> str:
    return str(norm_section(profile, section).get(key) or default)


def bool_value(profile: dict[str, Any], section: str, key: str, default: bool) -> bool:
    value = norm_section(profile, section).get(key, default)
    if isinstance(value, bool):
        return value
    return str(value).lower() in {"1", "true", "yes", "y"}


def managed_block(name: str, content: str, style: str) -> tuple[str, str, str]:
    if style == "html":
        begin = f"<!-- BEGIN MANAGED: init-harness {name} -->"
        end = f"<!-- END MANAGED: init-harness {name} -->"
    else:
        begin = f"# BEGIN MANAGED: init-harness {name}"
        end = f"# END MANAGED: init-harness {name}"
    body = content.strip("\n")
    return begin, end, f"{begin}\n{body}\n{end}\n"


def render_claude_block(profile: dict[str, Any]) -> str:
    paths = norm_section(profile, "paths")
    auth = norm_section(profile, "auth")
    contract = norm_section(profile, "project_contract")
    flows = contract.get("primary_flows") or []
    notes = contract.get("notes") or []
    flow_lines = "\n".join(f"- {item}" for item in flows) or "- 暂未声明"
    note_lines = "\n".join(f"- {item}" for item in notes) or "- 暂未声明"
    return f"""# 项目约定（由 init-harness 同步）

| 约定 | 本项目取值 |
|---|---|
| 项目名 | `{profile.get("project_name", "")}` |
| 站点基础 URL | `{profile.get("base_url", "")}` |
| 页面地图目录 | `{paths.get("page_map_dir", "page_map")}/` |
| 测试数据目录 | `{paths.get("data_dir", "data")}/` |
| 测试代码目录 | `{paths.get("tests_dir", "tests")}/` |
| artifact 目录 | `{paths.get("artifacts_dir", "artifacts")}/` |
| 测试运行命令 | `{scalar(profile, "runner", "test_command", "python -m pytest tests/ -v")}` |
| 登录逻辑 | `auth_mode={auth.get("auth_mode", "none")}`, needs_auth=`{auth.get("needs_auth", False)}` |

## 必读文件

- `rule.md`：selector、等待和断言红线。
- `artifacts/README.md`：多 agent 编排规范。
- 相关 `page_map/*.yaml`：当前页面元素地图。

## 首批建议业务流

{flow_lines}

## 项目注意事项

{note_lines}

## 开发原则

- 所有有意义字段都要断言。
- 禁止删除或弱化断言来让测试通过。
- selector 优先 ID、role、稳定属性和明确文本。
- 凭据只走环境变量，不写进仓库。
"""


def render_conftest_block(profile: dict[str, Any]) -> str:
    auth = norm_section(profile, "auth")
    needs_auth = bool_value(profile, "auth", "needs_auth", False)
    auth_mode = str(auth.get("auth_mode") or "none")

    if not needs_auth or auth_mode == "none":
        login_fixture = """@pytest.fixture
def app_page(page: Page):
    \"\"\"未登录页面入口；需要登录时改用 logged_in_page。\"\"\"
    return page
"""
    elif auth_mode == "basic":
        login_fixture = f"""@pytest.fixture
def logged_in_page(page: Page, base_url: str):
    \"\"\"基础账号密码登录 fixture；凭据来自环境变量。\"\"\"
    login_url = "{auth.get("login_url", "/login")}"
    target = f"{{base_url}}{{login_url}}" if login_url.startswith("/") else login_url
    page.goto(target)
    page.fill({auth.get("username_selector", 'input[name="email"]')!r}, os.environ["{auth.get("username_env", "E2E_USERNAME")}"])
    page.fill({auth.get("password_selector", 'input[name="password"]')!r}, os.environ["{auth.get("password_env", "E2E_PASSWORD")}"])
    page.click({auth.get("submit_selector", 'button[type="submit"]')!r})
    post_login = "{auth.get("post_login_url_pattern", "/")}"
    wait_target = f"{{base_url}}{{post_login}}" if post_login.startswith("/") else post_login
    page.wait_for_url(wait_target)
    return page
"""
    else:
        login_fixture = """@pytest.fixture
def logged_in_page(page: Page, base_url: str):
    \"\"\"自定义登录 fixture；请在 CUSTOM 区实现 custom_logged_in_page。\"\"\"
    return custom_logged_in_page(page, base_url)
"""

    return f"""import os
from pathlib import Path

import pytest
from playwright.sync_api import Page


@pytest.fixture(scope="session")
def project_root():
    return Path(__file__).resolve().parent


{login_fixture}"""


def render_conftest_custom_block() -> str:
    return """# 在这里放复杂登录 hook、租户选择、SSO 绕过或项目专属 fixture。
# 示例：
# def custom_logged_in_page(page, base_url):
#     page.goto(f"{base_url}/login")
#     ...
#     return page
"""


def render_pytest_ini(profile: dict[str, Any]) -> str:
    tests_dir = path_value(profile, "paths", "tests_dir", "tests")
    base_url = str(profile.get("base_url") or "https://example.com")
    return f"""# {MANAGED_FILE_MARKER}
[pytest]
addopts = --tb=short --base-url={base_url}
testpaths = {tests_dir}
"""


def render_env_example(profile: dict[str, Any]) -> str:
    auth = norm_section(profile, "auth")
    lines = [f"# {MANAGED_FILE_MARKER}", f"BASE_URL={profile.get('base_url', '')}"]
    if bool_value(profile, "auth", "needs_auth", False):
        lines.append(f"{auth.get('username_env', 'E2E_USERNAME')}=")
        lines.append(f"{auth.get('password_env', 'E2E_PASSWORD')}=")
    return "\n".join(lines).strip() + "\n"


def render_gitignore_block() -> str:
    return """.env
.env.*
!.env.example
test-results/
playwright-report/
.pytest_cache/
__pycache__/
data/debug/
artifacts/*/journal.jsonl
.claude/journal_task
"""


def render_requirements_block() -> str:
    return """pytest>=8.0
pytest-playwright>=0.5
playwright>=1.40
pyyaml>=6.0
"""


def render_rule_block() -> str:
    return """## Selector 优先级

1. 语义 ID / role：`#firstName`、`page.get_by_role(...)`
2. 稳定属性：`[data-testid=...]`、`[placeholder=...]`、`[href*=...]`
3. 明确文本：`get_by_text(...)`、`:has-text(...)`
4. 避免：hash class、`:nth-child`、xpath 位置索引

## 等待和断言

- 导航后优先等待 `networkidle` 或具体元素可见。
- 断言使用 Playwright `expect(...)` 的自动重试能力。
- 不用固定 sleep 迁就时序。

## 测试设计红线

- 不删除或弱化断言来让测试通过。
- `expected` 不使用空字符串、`0` 或 `-` 作为迁就值。
- 文本断言优先包含或 regex，避免脆弱精确匹配。
"""


class HarnessInitializer:
    def __init__(self, project_root: Path, apply: bool) -> None:
        self.root = project_root.resolve()
        self.apply = apply
        self.ops: list[Operation] = []

    def rel(self, path: Path) -> str:
        try:
            return str(path.resolve().relative_to(self.root))
        except ValueError:
            return str(path)

    def record(self, action: str, path: Path, detail: str, destructive: bool = False) -> None:
        self.ops.append(Operation(action, path, detail, destructive))

    def ensure_dir(self, path: Path) -> None:
        target = self.root / path
        if target.exists():
            self.record("unchanged", target, "directory exists")
            return
        self.record("mkdir", target, "create directory")
        if self.apply:
            target.mkdir(parents=True, exist_ok=True)

    def write_managed_file(self, relative: Path, content: str) -> None:
        target = self.root / relative
        if target.exists():
            old = target.read_text(encoding="utf-8")
            if old == content:
                self.record("unchanged", target, "managed file already current")
                return
            if MANAGED_FILE_MARKER not in old:
                self.record(
                    "manual",
                    target,
                    "exists without init-harness marker; review before replacing",
                )
                return
            self.record("update", target, "update managed file")
        else:
            self.record("create", target, "create managed file")
        if self.apply:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    def upsert_block(self, relative: Path, name: str, content: str, style: str) -> None:
        target = self.root / relative
        begin, end, block = managed_block(name, content, style)
        if target.exists():
            old = target.read_text(encoding="utf-8")
            if begin in old and end in old:
                before, rest = old.split(begin, 1)
                _, after = rest.split(end, 1)
                prefix = before.rstrip()
                suffix = after.lstrip("\n")
                new = prefix
                if new:
                    new += "\n\n"
                new += block
                if suffix:
                    new += "\n" + suffix
                action = "update" if new != old else "unchanged"
                detail = "replace managed block" if action == "update" else "managed block current"
            else:
                prefix = "" if old.endswith("\n") else "\n"
                new = old + prefix + "\n" + block
                action = "update"
                detail = "append managed block"
        else:
            new = block
            action = "create"
            detail = "create file with managed block"

        self.record(action, target, detail)
        if self.apply and action != "unchanged":
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(new, encoding="utf-8")

    def copy_template_tree(self) -> None:
        for template in TEMPLATES_DIR.rglob("*"):
            if template.is_dir():
                continue
            relative = template.relative_to(TEMPLATES_DIR)
            target = self.root / relative
            content = template.read_text(encoding="utf-8")
            if target.exists():
                old = target.read_text(encoding="utf-8")
                if old == content:
                    self.record("unchanged", target, "template already current")
                    continue
                if MANAGED_FILE_MARKER not in old:
                    self.record(
                        "manual",
                        target,
                        "exists without init-harness marker; review before replacing",
                    )
                    continue
                self.record("update", target, "update managed template")
            else:
                self.record("create", target, "create managed template")
            if self.apply:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(content, encoding="utf-8")

    def clean_demo_artifacts(self) -> None:
        candidates = [
            Path("page_map/testerhome"),
            Path("data/testerhome.yaml"),
            Path("tests/test_home.py"),
            Path("tests/test_search.py"),
        ]
        artifact_root = self.root / "artifacts"
        if artifact_root.exists():
            candidates.extend(
                p.relative_to(self.root)
                for p in artifact_root.iterdir()
                if p.is_dir() and "testerhome" in p.name.lower()
            )

        for relative in candidates:
            target = self.root / relative
            if not target.exists():
                continue
            if target.is_file():
                text = target.read_text(encoding="utf-8", errors="ignore")
                if "testerhome" not in text.lower() and "测试之家" not in text:
                    self.record("manual", target, "demo-like path but content is not clearly TesterHome")
                    continue
            self.record("delete", target, "remove known TesterHome demo artifact", destructive=True)
            if self.apply:
                if target.is_dir():
                    shutil.rmtree(target)
                else:
                    target.unlink()

    def sync(self, profile: dict[str, Any]) -> None:
        tests_dir = Path(path_value(profile, "paths", "tests_dir", "tests"))
        data_dir = Path(path_value(profile, "paths", "data_dir", "data"))
        page_map_dir = Path(path_value(profile, "paths", "page_map_dir", "page_map"))
        artifacts_dir = Path(path_value(profile, "paths", "artifacts_dir", "artifacts"))

        for directory in [
            tests_dir,
            data_dir,
            page_map_dir,
            artifacts_dir,
            Path(".claude/agents"),
            Path("scripts"),
        ]:
            self.ensure_dir(directory)

        self.copy_template_tree()
        self.write_managed_file(Path("pytest.ini"), render_pytest_ini(profile))
        self.write_managed_file(Path(".env.example"), render_env_example(profile))
        self.upsert_block(Path("CLAUDE.md"), "project-contract", render_claude_block(profile), "html")
        self.upsert_block(Path("conftest.py"), "fixtures", render_conftest_block(profile), "hash")
        self.upsert_block(
            Path("conftest.py"),
            "custom-auth-hooks",
            render_conftest_custom_block(),
            "hash",
        )
        self.upsert_block(Path(".gitignore"), "ignore-rules", render_gitignore_block(), "hash")
        self.upsert_block(
            Path("requirements.txt"),
            "python-deps",
            render_requirements_block(),
            "hash",
        )
        self.upsert_block(Path("rule.md"), "testing-rules", render_rule_block(), "html")
        self.clean_demo_artifacts()

    def print_plan(self) -> None:
        for op in self.ops:
            marker = "!" if op.destructive else "-"
            print(f"{marker} {op.action:9} {self.rel(op.path)} :: {op.detail}")

        summary: dict[str, int] = {}
        for op in self.ops:
            summary[op.action] = summary.get(op.action, 0) + 1
        print("\nSummary:")
        for action in sorted(summary):
            print(f"  {action}: {summary[action]}")

        manual = [op for op in self.ops if op.action == "manual"]
        if manual:
            print("\nManual attention required:")
            for op in manual:
                print(f"  - {self.rel(op.path)}: {op.detail}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", default=".", help="Target project root")
    parser.add_argument("--plan", action="store_true", help="Show plan only")
    parser.add_argument("--apply", action="store_true", help="Apply changes")
    args = parser.parse_args(argv)

    if args.plan and args.apply:
        parser.error("choose only one of --plan or --apply")

    project_root = Path(args.project_root).resolve()
    profile_path = project_root / PROFILE_NAME

    if not project_root.exists():
        print(f"Project root does not exist: {project_root}", file=sys.stderr)
        return 2

    if not profile_path.exists():
        profile_path.write_text(profile_draft(project_root), encoding="utf-8")
        print(f"Created draft profile: {profile_path}")
        print("Edit harness.project.yaml, then rerun init-harness in plan/apply mode.")
        return 0

    try:
        profile = load_profile(profile_path)
    except Exception as exc:  # noqa: BLE001
        print(f"Failed to read {profile_path}: {exc}", file=sys.stderr)
        return 2

    initializer = HarnessInitializer(project_root, apply=args.apply)
    initializer.sync(profile)
    initializer.print_plan()

    if not args.apply:
        print("\nPlan only. Rerun with --apply to write changes.")
    else:
        print("\nApplied changes.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
